name: release app

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: meetmarakana/Enforce-PR@1.1
      with:
        REQUIRED_LABELS_ANY: "bug,enhancement,skip-changelog"
        REQUIRED_LABELS_ANY_DESCRIPTION: "Select at least one label ['bug','enhancement','skip-changelog']"
        BANNED_LABELS: "banned"
