name: enforce_pr_label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    with:
          repository: meet-acko/enforce_label
          ref: main
          token: ${{ secrets.MY_TOKEN }}
