name: enforce_pr_label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ackotech/enforce-label
          ref: main
          token: dfc83ee9b2d75e5c0f341722e7acb8a62d1953f0
          path: .github/actions
      - uses: ./.github/actions/
        with:
          REQUIRED_LABELS_ANY: "feature,bug,enhancement"
          REQUIRED_LABELS_ALL: ""
          BANNED_LABELS: "banned"
