name: enforce-pr-label

on:
  pull_request:
    types: [labeled, unlabeled, opened, edited, synchronize]
jobs:
  enforce-label:
    runs-on: ubuntu-latest
    steps:
    - uses: meetmarakana/Enforce-PR@main
      with:
        REQUIRED_LABELS_ANY: "feature,bug,enhancement"
        REQUIRED_LABELS_ALL: ""
        BANNED_LABELS: "banned"
